name: flauto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  file_picker: ^9.0.2
  url_launcher: ^6.1.14
  html: ^0.15.4
  http: ^1.1.0
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^6.1.5
  mockito: ^5.4.0
  build_runner: ^2.3.3
  timezone: ^0.10.0
  intl: ^0.20.2
  table_calendar: ^3.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true